[build]
  publish = "blog/.vuepress/dist"
  command = "yarn fetch:posts && yarn build"

[context.production.environment]
  NODE_ENV = "production"
  DOMAIN = 'awzm.netlify.app'
  HOST = 'https://awzm.netlify.app'